apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-e03
  name: nginx-e03
  namespace: mathieu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-e03
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-e03
        episod: third
    spec:
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: gp2-chou
      containers:
        - image: nginx:latest
          name: nginx
          resources: {}
      initContainers:
        - name: init-container
          image: busybox
          volumeMounts:
            - name: pvc
              mountPath: /data
          envFrom:
            - configMapRef:
                name: nginx-e03
          command:
            [
              "sh",
              "-c",
              "echo $my_first_name >> /data/myfile && echo $my_last_name >> /data/myfile && date >> /data/myfile && cat /data/myfile",
            ]
status: {}
