apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-svc-2
  name: nginx-svc-2
  namespace: mathieu
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-e03-2
  type: LoadBalancer
status:
  loadBalancer: {}
