apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-svc
    episod: third
  name: nginx-svc
  namespace: mathieu
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-e03
    episod: third
  type: LoadBalancer 
status:
  loadBalancer: {}
