apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gp2-chou
  namespace: mathieu
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi